openapi: 3.0.1
info:
  title: Wallet API
  version: 1.0.0
paths:
  /user:
    get:
      security:
        - apiKey: []
      
      tags:
        - "Users"
      summary: Show all users
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - "Users"
      security:
        - apiKey: []
      summary: Add one or more user
      parameters:
        - name: "userID"
          in: path
          description: "ID of the user to be updated"
          required: true
          schema:
            type: string
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'
    delete:
      security:
        - apiKey: []
      tags:
        - "Users"
      summary: Delete all users
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'
    post:
      security:
        - apiKey: []
      tags:
        - "Users"
      summary: Create a new user
      requestBody:
        $ref: "#/components/requestBodies/UserRequestBody"
        
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'


  /user/{userID}:
    get:
      tags:
        - "Users"
      security:
        - apiKey: []
      summary: Show user(s) by ID
      parameters:
        - name: userID
          in: path
          required: true
          description : User's ID
          schema:
            type: string
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'
    delete:
      security:
        - apiKey: []
      tags:
        - "Users"
      summary: Delete user by ID
      parameters:
        - name: userID
          in: path
          description: "ID of the user to be deleted"
          required: true
          schema:
            type: string
      responses:
         '200':
           $ref: '#/components/responses/Success'
         '404':
           $ref: '#/components/responses/BadRequest'
         '500':
          $ref: '#/components/responses/ServerError'

components:
  responses:
    Success:
      description: Successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
          example: 
            success: true
        
              
    BadRequest:
      description: Bad Request
      content:
        application/json:
          example:
            error: "Bad Request"
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          example:
            error: "Internal Server Error"
  requestBodies:
    RequestBody:
      content:
        application/json:
          schema:
            type: object
    UserRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password: 
                type: string
            $ref: "#/components/schemas/User"
  securitySchemes:
    apiKey: 
      type: apiKey
      in: header
      name: Authorization
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Identifier for the user
        username:
          type: string
          minLength: 2
        password:
          type: string
      required:
        - "username"
        - "password"



